name: CI

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: test
        run: |
          npm install
          npm run test
